basePath: /
definitions:
  models.Address:
    properties:
      city:
        type: string
      line1:
        type: string
      line2:
        type: string
      postalCode:
        type: string
      state:
        type: string
    type: object
  models.Customer:
    properties:
      emailAddress:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      shippingAddress:
        $ref: '#/definitions/models.Address'
    type: object
  models.Health:
    properties:
      status:
        type: string
    type: object
  models.Order:
    properties:
      customer:
        $ref: '#/definitions/models.Customer'
      id:
        type: string
      products:
        items:
          $ref: '#/definitions/models.Product'
        type: array
    type: object
  models.Product:
    properties:
      productCode:
        type: string
      quantity:
        type: integer
    type: object
info:
  contact:
    email: your@mail.com
    name: API Support
  description: This is an auto-generated API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API
  version: "1.0"
paths:
  /health:
    get:
      description: Micro-service health check.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Health'
            type: array
      summary: micro-service health check
  /v1/order:
    post:
      consumes:
      - application/json
      description: Create a new order.
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Order'
      summary: create a new order
      tags:
      - Order
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
